### ISSUE TITLE
predicting log events - understanding dev-access.csv file

### ISSUE THREAD

**Issue by prashantgpt91** [adamkusey/securitai-lstm-model#1]
Hey @adamkusey 
I read your medium article related to this repo code. It's fantastic. 
I was trying to a dry run on your lstm model, but couldn't understand what this file `dev-access.csv` must have in order to do the prediction on a request log entry?

**Comment by adamkusey** [comment]
Thanks, I've added a sample csv so the training script can be tried out
https://github.com/adamkusey/securitai-lstm-model/pull/2
